const music_container = document.querySelector("#song-cont"), music_player = document.getElementById("audio-player"), songCurrentTime = document.getElementById("song-time-start"), songTotalTime = document.getElementById("song-total-time"), volume_control = document.getElementById("sound-unmute"); var currentSongObj = {}, defaultImage = "assets/images/defaultImage.gif"; function bootUpApp() { fetchAndRenderAllSections() } function fetchAndRenderAllSections() { fetch("assests/js/ganna.json").then(e => e.json()).then(e => { let { cardbox: n } = e; Array.isArray(n) && n.length && n.forEach(e => { let { songsbox: n, songscards: t } = e; renderSection(n, t) }) }).catch(e => { console.error(e), alert("Data not found") }) } function renderSection(e, n) { let t = makeSectionDom(e, n); music_container.appendChild(t) } function makeSectionDom(e, n) {
    let t = document.createElement("div"); return t.classList.add("dynamic-div"), t.style.marginBottom = "60px", t.innerHTML = `
        <h2 class="sec-heading">${e}</h2>
        <div class ="song-flex">
        ${n.map(e => buildSongCardDom(e)).join(" ")}
        </div >
    `, t
} function buildSongCardDom(e) {
    return `
    <div class="trending-songs" onclick="playSong(this)" data-songobj='${JSON.stringify(e)}'> 
        <div class="song-card">
            <img src="assets/images/${e.image_source}" alt="${e.song_name}">
                <img id="p-btn" src="https://a10.gaanacdn.com/gn_img/images/play_1621599900.png" class="play-button" alt="">
                    <h3>${e.song_name}</h3>
                </div>
        </div>

`} function playSong(e) { let n = JSON.parse(e.dataset.songobj); showLoadingOverlay(), setAndPlayCurrentSong(n) } function setAndPlayCurrentSong(e) { currentSongObj = e, music_player.pause(), music_player.src = e.quality.low, music_player.currentTime = 0, music_player.play(), music_player.addEventListener("canplay", hideLoadingOverlay), updatePlayerUi(e) } function showLoadingOverlay() { let e = document.getElementById("loading-overlay"); e.style.display = "block" } function hideLoadingOverlay() { let e = document.getElementById("loading-overlay"); e.style.display = "none" } function updatePlayerUi(e) { let n = document.getElementById("song-image"), t = document.getElementById("song-name"), a = document.getElementById("song-play-svg"), l = document.getElementById("song-pause-svg"), i = document.getElementById("song-play-btn"), s = document.getElementById("music-unmute"), o = document.getElementById("music-mute"); n.src = e.image_source, t.innerHTML = e.song_name, music_player.play() && (a.style.display = "none", l.style.display = "block"), music_player.play() && i.addEventListener("click", () => { music_player.pause(), a.style.display = "block", l.style.display = "none" }), i.addEventListener("dblclick", () => { music_player.play(), a.style.display = "none", l.style.display = "block" }), volume_control.addEventListener("click", () => { music_player.volume = 0, s.style.display = "block", o.style.display = "none" }), volume_control.addEventListener("dblclick", () => { music_player.volume = 1, s.style.display = "none", o.style.display = "block" }) } function updatePlayerTime() { music_player && !music_player.paused && (songCurrentTime.innerHTML = getTimeString(music_player.currentTime), isNaN(music_player.duration) ? songTotalTime.innerHTML = "00.00" : songTotalTime.innerHTML = getTimeString(music_player.duration)) } function getTimeString(e) { return isNaN(music_player.duration) ? "0:00" : Math.floor(e / 60) + ":" + parseInt((e / 60 % 1 * 60).toFixed(2)) } window.addEventListener("load", bootUpApp), music_player.addEventListener("pause", hideLoadingOverlay), music_player.addEventListener("ended", hideLoadingOverlay), music_player.addEventListener("timeupdate", updatePlayerTime); const v_low = document.getElementById("v-low"), v_med = document.getElementById("v-med"), v_high = document.getElementById("v-high"), update_volume = document.getElementById("update-volume"); v_low.addEventListener("click", e => { music_player.volume = .2, update_volume.innerHTML = e.target.innerHTML }), v_med.addEventListener("click", e => { music_player.volume = .6, update_volume.innerHTML = e.target.innerHTML }), v_high.addEventListener("click", e => { music_player.volume = 1, update_volume.innerHTML = e.target.innerHTML });
